/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.personaController;
import controller.vehiculoController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isaac
 */
public class asociarPersYCoche extends javax.swing.JFrame {

    private personaController personCtrl;
    private vehiculoController vehiculoCtrl;

    public asociarPersYCoche() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Asociar Vehiculos");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);

        personCtrl = new personaController();
        vehiculoCtrl = new vehiculoController();

        tblPersona.setModel(personCtrl.cargarPersonasTb());
        tblCoche.setModel(vehiculoCtrl.cargarVehiculoTb());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersona = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCoche = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAsociar = new javax.swing.JButton();
        btnEliminarAso = new javax.swing.JButton();
        checkAsociados = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPersona);
        if (tblPersona.getColumnModel().getColumnCount() > 0) {
            tblPersona.getColumnModel().getColumn(0).setResizable(false);
            tblPersona.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        tblCoche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Año", "Marca", "Modelo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCoche);
        if (tblCoche.getColumnModel().getColumnCount() > 0) {
            tblCoche.getColumnModel().getColumn(0).setResizable(false);
            tblCoche.getColumnModel().getColumn(1).setResizable(false);
            tblCoche.getColumnModel().getColumn(2).setResizable(false);
            tblCoche.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAsociar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAsociar.setText("ASOCIAR ");
        btnAsociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarActionPerformed(evt);
            }
        });

        btnEliminarAso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarAso.setText("ELIMINAR");
        btnEliminarAso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(btnAsociar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnEliminarAso, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarAso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsociar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        checkAsociados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkAsociados.setText("NO ASOCIADOS");
        checkAsociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAsociadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(checkAsociados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkAsociados)
                        .addGap(3, 3, 3)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkAsociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAsociadosActionPerformed
        // TODO add your handling code here:
        try {
            boolean mostrarNoAsociados = checkAsociados.isSelected();

            DefaultTableModel modeloPersonas = personCtrl.obtPerAso(mostrarNoAsociados);
            DefaultTableModel modeloVehiculos = vehiculoCtrl.obtVehiAso(mostrarNoAsociados);

            tblPersona.setModel(modeloPersonas);
            tblCoche.setModel(modeloVehiculos);

            if (mostrarNoAsociados) {
                btnAsociar.setEnabled(true);
            } else {
                btnAsociar.setEnabled(false);
            }

        } catch (Exception e) {
            System.out.println("Error al mostrar el filtro: " + e.getMessage());
        }
    }//GEN-LAST:event_checkAsociadosActionPerformed

    private void btnAsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarActionPerformed
        // TODO add your handling code here:
        int filaPerSeleccionada = tblPersona.getSelectedRow();
        int filaVehiSeleccionada = tblCoche.getSelectedRow();

        if (filaPerSeleccionada >= 0 && filaVehiSeleccionada >= 0) {
            String dni = (String) tblPersona.getValueAt(filaPerSeleccionada, 1);  // DNI de la persona
            String matricula = (String) tblCoche.getValueAt(filaVehiSeleccionada, 0);  // Matrícula del vehiculo

            try {
                boolean resultado = vehiculoCtrl.asoVehiConPer(dni, matricula);

                if (resultado) {
                    JOptionPane.showMessageDialog(this, "Vehiculo asociado con exito.");
                    tblPersona.setModel(personCtrl.cargarPersonasTb());
                    tblCoche.setModel(vehiculoCtrl.cargarVehiculoTb());
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo asociar el vehiculo.");
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al asociar vehiculo: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una persona y un vehiculo.");
        }

    }//GEN-LAST:event_btnAsociarActionPerformed

    private void btnEliminarAsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAsoActionPerformed
        // TODO add your handling code here:
        int filaPerSeleccionada = tblPersona.getSelectedRow();
        int filaVehiSeleccionada = tblCoche.getSelectedRow();

        if (filaPerSeleccionada >= 0 && filaVehiSeleccionada >= 0) {
            String dni = (String) tblPersona.getValueAt(filaPerSeleccionada, 1);  // el DNI esta en la segunda columna
            String matricula = (String) tblCoche.getValueAt(filaVehiSeleccionada, 0);  // la matricula esta en la primera columna

            try {
                // Llamamos al metodo para desasociar el vehiculo de la persona
                boolean exito = vehiculoCtrl.desasociarVehiculoDePersona(dni, matricula);

                if (exito) {
                    vehiculoCtrl.desasociarVehiculoDePersona(dni, matricula);

                    // Actualizar la fecha_fin del historial
                    vehiculoCtrl.actualizarFechaFinHistorial(dni, matricula);

                    JOptionPane.showMessageDialog(this, "Vehiculo desasociado con exito.");

                    // Actualizamos las tablas para reflejar los cambios
                    tblPersona.setModel(personCtrl.cargarPersonasTb());  // Recarga la tabla de personas
                    tblCoche.setModel(vehiculoCtrl.cargarVehiculoTb());  // Recarga la tabla de vehículos
                } else {
                    JOptionPane.showMessageDialog(this, "Error al desasociar el vehiculo.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al desasociar el vehiculo: " + e.getMessage());
                System.out.println("Error al desaciar: " + e.getMessage());
            }
        } else {
            // Si no se ha seleccionado una persona o vehiculo
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una persona y un vehiculo.");
        }
    }//GEN-LAST:event_btnEliminarAsoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asociarPersYCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asociarPersYCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asociarPersYCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asociarPersYCoche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asociarPersYCoche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsociar;
    private javax.swing.JButton btnEliminarAso;
    private javax.swing.JCheckBox checkAsociados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCoche;
    private javax.swing.JTable tblPersona;
    // End of variables declaration//GEN-END:variables
}
